sudo: false
language: python
python:
 - "3.4"
 - "3.5"
 - "3.6"
install:
  - pip install tox-travis
  - pip install "coverage>=3.7.1" coveralls
script: tox
after_success:
  - coverage report
  - coveralls
